### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by PortableGames** [Tschipcraft/deathanimations_test#1]
Textures don't work on 1.19.3 version... mob breaks into monochrome pieces . But otherwise a brilliant datapack

**Comment by Tschipcraft** [comment]
Thanks <3

**Comment by PortableGames** [comment]
I was fixing some datapacks that also had broken textures on 1.19.3. And I came up with a simple solution. Just move the textures to the minecraft/textures/block folder. There it can already be in any subfolder (textures/block/mytextures) and in the model just edit the path to the texture ("textures": {"1": "block/mytextures/somepngfile",). Then the texture will load fine. Maybe this advice will help you.

**Comment by Tschipcraft** [comment]
I got it working with the new atlas files, but thanks for the help 🎉
